{
 "title": "Database Hive Overview",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" },
   { "name": "txtype", "label": "Tx type", "query": { "query": "label_values(__name__)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU usage by HIVE_ACTOR, HIVE_BALANCER_ACTOR",
   "type": "timeseries",
   "description": "CPU time utilized by `HIVE_ACTOR` and `HIVE_BALANCER_ACTOR`, two of the most important actors of the Hive tablet",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(rate(utils_ElapsedMicrosecByActivity{execpool=\"System\", activity=\"HIVE_ACTOR\", database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "HIVE_ACTOR"
    },
    {
     "expr": "max(rate(utils_ElapsedMicrosecByActivity{execpool=\"System\", activity=\"HIVE_BALANCER_ACTOR\", database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "HIVE_BALANCER_ACTOR"
    }
   ]
  },
  {
   "title": "Tablet count",
   "type": "timeseries",
   "description": "Total number of tablets in the database",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(tablets_MAX_Hive_TabletsTotal_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "TabletsTotal"
    },
    {
     "expr": "max(tablets_MAX_Hive_TabletsAlive_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "TabletsAlive"
    },
    {
     "expr": "max(tablets_SUM_Hive_TabletsStarting_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "TabletsStarting"
    }
   ]
  },
  {
   "title": "Self-ping time",
   "type": "timeseries",
   "description": "Time it takes Hive to respond to itself. High values indicate heavy load (and low responsiveness) of the Hive",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(tablets_MAX_Hive_ResponseTimeMicrosec_{database=\"$database\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Event queue size",
   "type": "timeseries",
   "description": "Size of the incoming event queue in Hive. Consistently high values indicate Hive cannot process events fast enough",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "max(tablets_SUM_Hive_EventQueueSize_{database=\"$database\", type=\"Hive\", category=\"app\"})",
     "legendFormat": "EventQueueSize"
    }
   ]
  },
  {
   "title": "Local transaction times",
   "type": "timeseries",
   "description": "CPU time utilized by various local transaction types in Hive. Shows the structure of Hive load based on different activities.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "((label_replace({database=\"$database\",category=\"app\", type = \"Hive\", __name__=~\"tablets_MAX_Hive_Tx.*_ExecuteCPUTime_\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_MAX_Hive_Tx(.*)_ExecuteCPUTime_\")))",
     "legendFormat": "{{name_label}}"
    },
    {
     "expr": "max_over_time(sum({database=\"$database\",category=\"app\", type = \"Hive\", __name__=~\"tablets_MAX_Hive_Tx.*_ExecuteCPUTime_\"})[15m:])",
     "legendFormat": "ExecuteCpuTime total"
    }
   ]
  },
  {
   "title": "$txtype average time",
   "type": "timeseries",
   "description": "Average execution time of a single local hive transaction of the type specified in the `Tx type` parameter selector on the dashboard.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max((rate(tablets_Hive_${txtype}_RoCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])) + (rate(tablets_Hive_${txtype}_RwCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])))",
     "legendFormat": "$txtype count"
    },
    {
     "expr": "max((tablets_MAX_Hive_${txtype}_ExecuteCPUTime_{database=\"$database\",category=\"app\",type=\"Hive\"}) / ((rate(tablets_Hive_${txtype}_RoCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])) + (rate(tablets_Hive_${txtype}_RwCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval]))))",
     "legendFormat": "$txtype average time"
    },
    {
     "expr": "max(max_over_time(((rate(tablets_Hive_${txtype}_RoCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])) + (rate(tablets_Hive_${txtype}_RwCompleted{database=\"$database\",category=\"app\",type=\"Hive\"}[$__rate_interval])))[15m:]))",
     "legendFormat": "$txtype count, total on 15 min window"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "description": "Versions of YDB running on cluster nodes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "count by (revision) (utils_version{database=\"$database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hive node",
   "type": "timeseries",
   "description": "Node where the database Hive is running",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "utils_ActorsAliveByActivity{activity=\"HIVE_ACTOR\", execpool=\"System\", database=\"$database\"}",
     "legendFormat": "{{instance}} ({{host}})"
    }
   ]
  }
 ]
}