{
 "title": "Database hive balance",
 "description": "See Hive documentation here: https://ydb.tech/docs/en/contributor/hive?version=main",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "See Hive documentation at https://ydb.tech/docs/en/contributor/hive?version=main"
   }
  },
  {
   "title": "Tablet moved per second",
   "type": "timeseries",
   "description": "Tablets can be moved by Balancer, Drain or Fill",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(tablets_Hive_TabletsMoved{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "Tablets moved per second"
    }
   ]
  },
  {
   "title": "Subactor runs per second",
   "type": "timeseries",
   "description": "Balancer runs are (usually) automatically triggered when imbalance is detected.\n\nDrain and Fill are triggered by outside queries.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(tablets_Hive_DrainExecuted{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "DrainExecuted"
    },
    {
     "expr": "max(rate(tablets_Hive_AutokickExecuted{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "AutokickExecuted"
    },
    {
     "expr": "max(rate(tablets_Hive_FillExecuted{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "FillExecuted"
    },
    {
     "expr": "max(rate(tablets_Hive_StorageBalancerExecuted{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "StorageBalancerExecuted"
    },
    {
     "expr": "max(rate(tablets_Hive_BalancerExecuted{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "BalancerExecuted"
    }
   ]
  },
  {
   "title": "Suggestions per second",
   "type": "timeseries",
   "description": "SuggestedScaleUp means all nodes are overloaded, while SuggestedScaleDown means all nodes are underloaded",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(tablets_Hive_SuggestedScaleDown{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "SuggestedScaleDown"
    },
    {
     "expr": "max(rate(tablets_Hive_SuggestedScaleUp{database=\"$database\"}[$__rate_interval]))",
     "legendFormat": "SuggestedScaleUp"
    }
   ]
  },
  {
   "title": "Node usage max/min/scatter",
   "type": "timeseries",
   "description": "Node usage max/min/scatter",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(tablets_MAX_Hive_BalanceUsageMax_{database=\"$database\"})",
     "legendFormat": "BalanceUsageMax"
    },
    {
     "expr": "max(tablets_MAX_Hive_BalanceUsageMin_{database=\"$database\"})",
     "legendFormat": "BalanceUsageMin"
    },
    {
     "expr": "max(tablets_MAX_Hive_BalanceScatter_{database=\"$database\"})",
     "legendFormat": "BalanceScatter"
    }
   ]
  },
  {
   "title": "Node usage",
   "type": "timeseries",
   "description": "Nodes counted distributed by usage buckets",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (le) (tablets_Hive_NodeUsage_bucket{database=\"$database\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Tablets total",
   "type": "timeseries",
   "description": "Total number of tablets in the database",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max(tablets_MAX_Hive_TabletsTotal_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "TabletsTotal"
    },
    {
     "expr": "max(tablets_MAX_Hive_TabletsAlive_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "TabletsAlive"
    },
    {
     "expr": "max(tablets_SUM_Hive_TabletsStarting_{type=\"Hive\", category=\"app\", database=\"$database\"})",
     "legendFormat": "TabletsStarting"
    }
   ]
  },
  {
   "title": "Boot Queue size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_Hive_BootQueueSize_{database=\"$database\"})",
     "legendFormat": "BootQueueSize"
    },
    {
     "expr": "sum(tablets_SUM_Hive_WaitQueueSize_{database=\"$database\"})",
     "legendFormat": "WaitQueueSize"
    }
   ]
  },
  {
   "title": "Nodes total",
   "type": "timeseries",
   "description": "Total number of nodes in the database",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max(tablets_MAX_Hive_NodesTotal_{database=\"$database\"})",
     "legendFormat": "NodesTotal"
    },
    {
     "expr": "max(tablets_MAX_Hive_NodesConnected_{database=\"$database\"})",
     "legendFormat": "NodesConnected"
    }
   ]
  },
  {
   "title": "Tablets Start Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tablets_Hive_TabletsStartTimeMs_bucket{database=\"$database\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(tablets_Hive_TabletsStartTimeMs_bucket{database=\"$database\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(tablets_Hive_TabletsStartTimeMs_bucket{database=\"$database\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tablets_Hive_TabletsStartTimeMs_bucket{database=\"$database\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Nodes down/frozen",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "max(tablets_MAX_Hive_NodesDown_{database=\"$database\"})",
     "legendFormat": "NodesDown"
    },
    {
     "expr": "max(tablets_MAX_Hive_NodesFrozen_{database=\"$database\"})",
     "legendFormat": "NodesFrozen"
    }
   ]
  },
  {
   "title": "Hive node",
   "type": "timeseries",
   "description": "Node where the database Hive is running",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "utils_ActorsAliveByActivity{activity=\"HIVE_ACTOR\", execpool=\"System\", database=\"$database\"}",
     "legendFormat": "{{instance}} ({{host}})"
    }
   ]
  }
 ]
}