{
 "title": "Distributed Storage Self Heal",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CMS total PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(tablets_PDisksTotal)", "legendFormat": "PDisksTotal" }
   ]
  },
  {
   "title": "CMS PDisk change",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(tablets_PDisksTotal)", "legendFormat": "PDisksTotal" },
    { "expr": "sum(tablets_PDisksChanged)", "legendFormat": "PDisksChanged" },
    { "expr": "sum(tablets_PDisksNotChanged)", "legendFormat": "PDisksNotChanged" },
    {
     "expr": "sum(tablets_PDisksPendingChange)",
     "legendFormat": "PDisksPendingChange"
    }
   ]
  },
  {
   "title": "BSC Reassign requests/responses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(tablets_BSController_SelfHealReassignBscErr[$__rate_interval]))",
     "legendFormat": "SelfHealReassignBscErr"
    },
    {
     "expr": "sum(rate(tablets_BSController_SelfHealReassignBscOk[$__rate_interval]))",
     "legendFormat": "SelfHealReassignBscOk"
    },
    {
     "expr": "sum(rate(tablets_BSController_SelfHealReassignBscRequests[$__rate_interval]))",
     "legendFormat": "SelfHealReassignBscRequests"
    }
   ]
  },
  {
   "title": "BSC Unreassignable Groups",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "max(MAX_BSController_SelfHealUnreassignableGroups_{__workspace__=\"$workspace\",__bucket__=\"tablets\"})",
     "legendFormat": "UnreassignableGroups"
    },
    {
     "expr": "max(tablets_MAX_BSController_SelfHealUnreassignableGroups_)",
     "legendFormat": "UnreassignableGroups"
    }
   ]
  },
  {
   "title": "BSC Faulty Unsettled PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(le) (rate(BSController_FaultyUnsettledPDisks_bucket{__workspace__=\"$workspace\", __bucket__=\"tablets\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "sum by(le) (rate(tablets_BSController_FaultyUnsettledPDisks_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "BSC bytes on faulty PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(SUM_BSController_BytesOnFaultyDisks_{__workspace__=\"$workspace\",__bucket__=\"tablets\"})",
     "legendFormat": "BytesOnFaultyDisks"
    },
    {
     "expr": "sum(tablets_SUM_BSController_BytesOnFaultyDisks_)",
     "legendFormat": "BytesOnFaultyDisks"
    }
   ]
  },
  {
   "title": "BSC vslots on faulty PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_BSController_SlotsOnFaultyDisks_)",
     "legendFormat": "SlotsOnFaultyDisks"
    }
   ]
  },
  {
   "title": "BSC groups with vslot on faulty PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(SUM_BSController_GroupsWithSlotsOnFaultyDisks_{__workspace__=\"$workspace\",__bucket__=\"tablets\"})",
     "legendFormat": "GroupsWithSlotsOnFaultyDisks"
    },
    {
     "expr": "sum(tablets_SUM_BSController_GroupsWithSlotsOnFaultyDisks_)",
     "legendFormat": "GroupsWithSlotsOnFaultyDisks"
    }
   ]
  },
  {
   "title": "BSC ToBeRemoved Unsettled PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(le) (rate(tablets_BSController_ToBeRemovedUnsettledPDisks_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BSC bytes on ToBeRemoved PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_BSController_BytesOnToBeRemovedDisks_)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BSC vslots on ToBeRemoved PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_BSController_SlotsOnToBeRemovedDisks_)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BSC groups with vslot on ToBeRemoved PDisks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(tablets_SUM_BSController_GroupsWithSlotsOnToBeRemovedDisks_)",
     "legendFormat": "GroupsWithSlotsOnToBeRemovedDisks"
    }
   ]
  }
 ]
}