{
 "title": "Distributed Storage Performance Metrics",
 "tags": [ "ydb" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "storagePool", "label": "storagePool", "query": { "query": "label_values(storagePool)" } },
   {
    "name": "storageGroup",
    "label": "storageGroup",
    "query": {
     "query": "label_values({storagePool=\"$storagePool\"},group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DiskTimeAvailable and total Cost relation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(vdisks_DiskTimeAvailable{storagePool=\"$storagePool\", group=~\"$storageGroup\"})",
     "legendFormat": "DiskTimeAvailable"
    },
    {
     "expr": "(sum(rate(vdisks_UserDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))) + (sum(rate(vdisks_InternalDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))) + (sum(rate(vdisks_CompactionDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))) + (sum(rate(vdisks_DefragDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))) + (sum(rate(vdisks_ScrubDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval])))",
     "legendFormat": "Total Cost"
    }
   ]
  },
  {
   "title": "Cost by source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(vdisks_UserDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))",
     "legendFormat": "UserDiskCost"
    },
    {
     "expr": "sum(rate(vdisks_InternalDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))",
     "legendFormat": "InternalDiskCost"
    },
    {
     "expr": "sum(rate(vdisks_CompactionDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))",
     "legendFormat": "CompactionDiskCost"
    },
    {
     "expr": "sum(rate(vdisks_DefragDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))",
     "legendFormat": "DefragDiskCost"
    },
    {
     "expr": "sum(rate(vdisks_ScrubDiskCost{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))",
     "legendFormat": "ScrubDiskCost"
    }
   ]
  },
  {
   "title": "Total burst duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(vdisks_BurstDetector_redMs{storagePool=\"$storagePool\", group=~\"$storageGroup\"}[$__rate_interval]))",
     "legendFormat": "BurstTime"
    }
   ]
  }
 ]
}