{
 "title": "Distributed Storage Replication Factor",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overall cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Space bytes by levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pdisks_UsedSpaceBytes{container=~\"ydb-static|ydb-storage\"})",
     "legendFormat": "pdisk bytes"
    },
    {
     "expr": "sum(tablets_MAX_SchemeShard_DiskSpaceTablesDataBytes_{container=\"ydb-dynamic\"})",
     "legendFormat": "user bytes"
    },
    {
     "expr": "sum(vdisks_HugeUsedChunks{container=~\"ydb-static|ydb-storage\"}) * 128 * 1024 * 1024",
     "legendFormat": "huge total bytes"
    },
    {
     "expr": "sum(vdisks_DskSpaceCurInplacedData{container=~\"ydb-static|ydb-storage\"})",
     "legendFormat": "sst bytes"
    },
    {
     "expr": "sum(vdisks_DskSpaceCompInplacedData{container=\"ydb-dynamic\"})",
     "legendFormat": "sst comp bytes"
    },
    { "expression": "$C - $D", "type": "math" }
   ]
  },
  {
   "title": "Space amplification by levels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expression": "$A / $B", "type": "math" },
    { "expression": "$C / ($C - $D)", "type": "math" },
    { "expression": "($F + $C - $D) / $B", "type": "math" },
    { "expression": "$A / ($C + $E)", "type": "math" },
    { "expression": "$E / $F", "type": "math" }
   ]
  },
  {
   "title": "DsProxy write amplification",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(dsproxynode_requestBytes{container=\"ydb-dynamic\", handleClass=~\"Put.+\"}[$__rate_interval]))",
     "legendFormat": "Put* requestBytes"
    },
    {
     "expr": "sum(rate(dsproxynode_generatedSubrequestBytes{container=\"ydb-dynamic\", handleClass=~\"Put.+\"}[$__rate_interval]))",
     "legendFormat": "Put* generatedSubrequestBytes"
    },
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": " Fragmentation detalization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(vdisks_HugeUsedChunks{container=~\"ydb-static|ydb-storage\"})",
     "legendFormat": "huge used chunks"
    },
    {
     "expr": "sum(vdisks_HugeCanBeFreedChunks{container=~\"ydb-static|ydb-storage\"})",
     "legendFormat": "huge can be freed chunks"
    },
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  { "title": "By database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Space bytes by database",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (database) (tablets_MAX_SchemeShard_DiskSpaceTablesDataBytes_{container=\"ydb-dynamic\"})",
     "legendFormat": "user bytes {{database}}"
    }
   ]
  },
  { "title": "By media", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Space bytes by levels ssd",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pdisks_UsedSpaceBytes{container=~\"ydb-static|ydb-storage\", media=\"ssd\"})",
     "legendFormat": "pdisk bytes"
    },
    {
     "expr": "sum(vdisks_HugeUsedChunks{container=~\"ydb-static|ydb-storage\", media=\"ssd\"}) * 128 * 1024 * 1024",
     "legendFormat": "huge total bytes"
    },
    {
     "expr": "sum(vdisks_DskSpaceCurInplacedData{container=~\"ydb-static|ydb-storage\", media=\"ssd\"})",
     "legendFormat": "sst bytes"
    },
    {
     "expr": "sum(vdisks_DskSpaceCompInplacedData{container=\"ydb-dynamic\", media=\"ssd\"})",
     "legendFormat": "sst comp bytes"
    },
    { "expression": "$C - $D", "type": "math" }
   ]
  },
  {
   "title": "Space bytes by levels rot",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pdisks_UsedSpaceBytes{container=~\"ydb-static|ydb-storage\", media=\"rot\"})",
     "legendFormat": "pdisk bytes"
    },
    {
     "expr": "sum(vdisks_HugeUsedChunks{container=~\"ydb-static|ydb-storage\", media=\"rot\"}) * 128 * 1024 * 1024",
     "legendFormat": "huge total bytes"
    },
    {
     "expr": "sum(vdisks_DskSpaceCurInplacedData{container=~\"ydb-static|ydb-storage\", media=\"rot\"})",
     "legendFormat": "sst bytes"
    },
    {
     "expr": "sum(vdisks_DskSpaceCompInplacedData{container=\"ydb-dynamic\", media=\"rot\"})",
     "legendFormat": "sst comp bytes"
    },
    { "expression": "$C - $D", "type": "math" }
   ]
  },
  {
   "title": "DsProxy write amplification ssd",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(dsproxynode_requestBytes{container=\"ydb-dynamic\", handleClass=~\"Put.+\", storagePool=~\".*ssd.*\"}[$__rate_interval]))",
     "legendFormat": "Put* requestBytes"
    },
    {
     "expr": "sum(rate(dsproxynode_generatedSubrequestBytes{container=\"ydb-dynamic\", handleClass=~\"Put.+\", storagePool=~\".*ssd.*\"}[$__rate_interval]))",
     "legendFormat": "Put* generatedSubrequestBytes"
    },
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "DsProxy write amplification rot",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(dsproxynode_requestBytes{container=\"ydb-dynamic\", handleClass=~\"Put.+\", storagePool=~\".*rot.*\"}[$__rate_interval]))",
     "legendFormat": "Put* requestBytes"
    },
    {
     "expr": "sum(rate(dsproxynode_generatedSubrequestBytes{container=\"ydb-dynamic\", handleClass=~\"Put.+\", storagePool=~\".*rot.*\"}[$__rate_interval]))",
     "legendFormat": "Put* generatedSubrequestBytes"
    },
    { "expression": "$B / $A", "type": "math" }
   ]
  }
 ]
}