{
 "title": "PDisk Device single disk",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "media", "label": "media", "query": { "query": "label_values(media)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"ydb/pdisks\"},instance)"
    }
   },
   { "name": "pod", "label": "pod (for k8s)", "query": { "query": "label_values(pod)" } },
   { "name": "pdisk", "label": "pdisk", "query": { "query": "label_values(pdisk)" } }
  ]
 },
 "panels": [
  {
   "title": "Device Reads/Writes/Seeks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pdisks_DeviceReads{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "DeviceReads"
    },
    {
     "expr": "sum(rate(pdisks_DeviceWrites{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "DeviceWrites"
    },
    {
     "expr": "sum(rate(pdisks_DeviceExpectedSeeks{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "DeviceExpectedSeeks"
    }
   ]
  },
  {
   "title": "Device Bytes Read/Written",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(pdisks_DeviceBytesRead{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "DeviceBytesRead"
    },
    {
     "expr": "sum(rate(pdisks_DeviceBytesWritten{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "DeviceBytesWritten"
    }
   ]
  },
  {
   "title": "Priority Class Bytes Read/Write Requested (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (req) (rate(pdisks_Bytes{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{req}}"
    }
   ]
  },
  {
   "title": "Device InFlight Bytes Read/Written",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(pdisks_DeviceInFlightBytesRead{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(pdisks_DeviceInFlightBytesWrite{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(pdisks_QueueBytes{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QueueBytes"
    }
   ]
  },
  {
   "title": "Device InFlght Reads/Writes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(pdisks_DeviceInFlightReads{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(pdisks_DeviceInFlightWrites{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(rate(pdisks_QueueRequests{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QueueRequests"
    }
   ]
  },
  {
   "title": "Device write duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (rate(pdisks_deviceWriteDurationMs_bucket{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Device read duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (le) (rate(pdisks_deviceReadDurationMs_bucket{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Device trim duration (512 cap)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (le) (rate(pdisks_deviceTrimDurationMs_bucket{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DeviceActualCostNs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(pdisks_DeviceActualCostNs{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "DeviceActualCostNs"
    }
   ]
  },
  {
   "title": "L6 red (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pdisks_L6_redMs{container=~\"ydb-static|ydb-storage\", media=\"$media\", pdisk=\"$pdisk\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{media}}:{{pdisk}}"
    }
   ]
  },
  {
   "title": "Device Overestimation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "pdisks_DeviceOverestimationRatio{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", instance=\"$instance\"}",
     "legendFormat": "DeviceOverestimationRatio"
    }
   ]
  },
  {
   "title": "VDisk compactions (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(vdisks_LsmCompactionBytesRead{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", subsystem=\"lsmhull\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "LsmCompactionBytes Read"
    },
    {
     "expr": "sum(rate(vdisks_LsmCompactionBytesWritten{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", subsystem=\"lsmhull\"}[$__rate_interval]))",
     "legendFormat": "LsmCompactionBytes Written"
    }
   ]
  },
  {
   "title": "Device write cache is valid/enabled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(pdisks_DeviceWriteCacheIsValid{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\"}[$__rate_interval]))",
     "legendFormat": "DeviceWriteCacheIsValid"
    },
    {
     "expr": "sum(rate(pdisks_DeviceWriteCacheIsEnabled{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\"}[$__rate_interval]))",
     "legendFormat": "DeviceWriteCacheIsEnabled"
    }
   ]
  },
  {
   "title": "(FIXME) Device write duration (ms) ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by(group) (rate(vdisks_LatencyMs_count{container=~\"ydb-static|ydb-storage\", media=\"$media\", pod=\"$pod\", pdisk=\"$pdisk\", handleclass=\"PutTabletLog\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{group}}:{{le}}"
    }
   ]
  }
 ]
}