{
 "title": "YDB Essential Metrics",
 "tags": [ "ydb" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "database", "query": { "query": "label_values(database)" } }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "#### Health" } },
  {
   "title": "Nodes count",
   "type": "timeseries",
   "description": "Displays the current number of nodes",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count(utils_Process_UptimeSeconds{container=\"ydb-dynamic\", database=\"$database\"})",
     "legendFormat": "dynnodes"
    },
    {
     "expr": "count(utils_Process_UptimeSeconds{container=\"ydb-static\"})",
     "legendFormat": "storage nodes"
    }
   ]
  },
  {
   "title": "Nodes Uptime",
   "type": "timeseries",
   "description": "Displays the uptime of each node since its startup. Helps track restarts and identify unstable nodes.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "utils_Process_UptimeSeconds{container=\"ydb-dynamic\", database=\"$database\"}",
     "legendFormat": "dynnode: {{host}}"
    },
    {
     "expr": "utils_Process_UptimeSeconds{container=\"ydb-static\"}",
     "legendFormat": "storage node: {{instance}}"
    }
   ]
  },
  {
   "title": "VDisks count",
   "type": "timeseries",
   "description": "Displays the current number of VDisks",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "targets": [
    { "expr": "sum(vdisks_count)", "legendFormat": "VDisks count" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 }, "options": { "content": "#### Saturation" } },
  {
   "title": "CPU by thread pool (dynnodes)",
   "type": "timeseries",
   "description": "Shows CPU usage by thread pool of dynamic nodes. More on CPU pools: https://ydb.tech/docs/en/devops/configuration-management/configuration-v2/config-settings#tuneconfig",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (execpool) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])/1000000)",
     "legendFormat": "{{execpool}}"
    }
   ]
  },
  {
   "title": "CPU utilization (dynnodes)",
   "type": "timeseries",
   "description": "Displays the percentage of allocated CPU resources used by dynamic nodes broken down by pools. Helps identify CPU resource shortages. More on CPU pools: https://ydb.tech/docs/en/devops/configuration-management/configuration-v2/config-settings#tuneconfig",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    sum(rate(ydb_resources_cpu_used_core_percents{database=\"$database\"}[$__rate_interval])) \n    / \n    sum(ydb_resources_cpu_total_core_percents{database=\"$database\"})\n  )\n  and on()\n  (\n    sum(ydb_resources_cpu_limit_core_percents{database=\"$database\"}) \n    > \n    sum(ydb_resources_cpu_total_core_percents{database=\"$database\"})\n  ),\n  \"pool\", \"CPU utilization\", \"\", \"\"\n)\n\nor\n\n(\n  (sum by (pool) (rate(ydb_resources_cpu_used_core_percents{database=\"$database\", container=\"ydb-dynamic\"}[$__rate_interval]))) \n  / \n  (sum by (pool) (ydb_resources_cpu_limit_core_percents{database=\"$database\", container=\"ydb-dynamic\"}))\n)\n* on() group_left()\n(\n  sum(ydb_resources_cpu_limit_core_percents{database=\"$database\"}) \n  <= bool \n  sum(ydb_resources_cpu_total_core_percents{database=\"$database\"})\n)\n!= 0\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elapsed Time vs CPU Time",
   "type": "timeseries",
   "description": "Shows Elapsed µs vs CPU µs per node. If the ratio is > 100%, CPU time exceeds Elapsed time, which most likely indicates CPU overcommit.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (host) (rate(utils_ElapsedMicrosec{database=\"$database\"}[$__rate_interval]))) / (sum by (host) (rate(utils_CpuMicrosec{database=\"$database\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    { "expr": "vector(1)", "legendFormat": "100%" }
   ]
  },
  {
   "title": "RSS size by node",
   "type": "timeseries",
   "description": "Displays the amount of RAM (Resident Set Size) consumed by each node.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (host, pod) (utils_Process_AnonRssSize{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "dynnode: {{host}}{{pod}}"
    },
    {
     "expr": "sum by (instance) (utils_Process_AnonRssSize{container=\"ydb-static\"})",
     "legendFormat": "storage node: {{instance}}"
    },
    {
     "expr": "min(utils_Process_CGroupMemLimit{database=\"$database\"})",
     "legendFormat": "CGroup memory limit dynnodes"
    },
    {
     "expr": "min(utils_Process_CGroupMemLimit{database=\"\"})",
     "legendFormat": "CGroup memory limit storage nodes"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "description": "Shows overall usage and limit of the total size of database tables. Helps prevent storage space shortage issues.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ydb_resources_storage_used_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(ydb_resources_storage_limit_bytes{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Overloaded shard count",
   "type": "timeseries",
   "description": "Shows the number of shards experiencing high CPU load (from 50% to 100%). Helps assess the level of system overload.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"50%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "50%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"60%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "60%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"70%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "70%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"80%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "80%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"90%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "90%"
    },
    {
     "expr": "sum(tablets_HIST_ConsumedCPU_{range=\"100%\", type=\"DataShard\", database=\"$database\"})",
     "legendFormat": "100%"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 }, "options": { "content": "#### Traffic" } },
  {
   "title": "Queries per second by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of queries per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(ydb_table_query_execution_latency_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions per second by latency buckets",
   "type": "timeseries",
   "description": "Displays the number of transactions per second grouped by latency bins.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(ydb_table_transaction_total_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rows read, uploaded, updated, deleted",
   "type": "timeseries",
   "description": "Displays the number of rows per second affected by corresponding operations.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "(sum(rate(tablets_DataShard_EngineHostRowUpdates{database=\"$database\"}[$__rate_interval])) or vector(0)) +\n(sum(rate(followers_DataShard_EngineHostRowUpdates{database=\"$database\"}[$__rate_interval])) or vector(0))",
     "legendFormat": "Updated"
    },
    {
     "expr": "(sum(rate(tablets_DataShard_EngineHostRowReads{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])) or vector(0)) + \n(sum (rate(tablets_DataShard_EngineHostRangeReadRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])) or vector(0))+ \n(sum (rate(followers_DataShard_EngineHostRowReads{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])) or vector(0))+ \n(sum (rate(followers_DataShard_EngineHostRangeReadRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])) or vector(0))",
     "legendFormat": "Read"
    },
    {
     "expr": "(sum (rate(tablets_DataShard_EngineHostRowErases{database=\"$database\"}[$__rate_interval])) or vector(0)) + \n(sum (rate(followers_DataShard_EngineHostRowErases{database=\"$database\"}[$__rate_interval])) or vector(0))",
     "legendFormat": "Deleted"
    },
    {
     "expr": "(sum(rate(tablets_DataShard_UploadRows{database=\"$database\"}[$__rate_interval])) or vector(0)) + \n(sum(rate(followers_DataShard_UploadRows{database=\"$database\"}[$__rate_interval])) or vector(0))",
     "legendFormat": "Uploaded"
    }
   ]
  },
  {
   "title": "Session count by dynnode",
   "type": "timeseries",
   "description": "Displays the number of active sessions per dynamic node. Helps identify uneven session distribution.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "sum by (host, pod) (kqp_SessionActors_Active{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 26 }, "options": { "content": "#### Latency" } },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 26 }, "options": { "content": "#### Errors" } },
  {
   "title": "Query latency percentiles (ms)",
   "type": "timeseries",
   "description": "Displays percentiles of query execution time.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(ydb_table_query_execution_latency_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(ydb_table_query_execution_latency_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(ydb_table_query_execution_latency_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(ydb_table_query_execution_latency_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Transaction latency percentiles (ms)",
   "type": "timeseries",
   "description": "Displays percentiles of transaction execution time.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(ydb_table_transaction_total_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(ydb_table_transaction_total_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(ydb_table_transaction_total_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(ydb_table_transaction_total_duration_milliseconds_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "YQL Issues per second",
   "type": "timeseries",
   "description": "Displays the number of errors occurred during YQL queries execution.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "sum by (name_label) (\n  rate(\n    label_replace(\n      {database=\"$database\", container=\"ydb-dynamic\", __name__=~\"kqp_Issues_YQL:.+\"},\n      \"name_label\", \"$1\", \"__name__\", \"kqp_Issues_YQL:(.+)\"\n    )[$__rate_interval:]\n  )\n) or\nlabel_replace(vector(0), \"name_label\", \"No Errors\", \"\", \"\")\n\n",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "GRPC response errors per second",
   "type": "timeseries",
   "description": "Displays the number of gRPC response errors per second by type.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(ydb_api_grpc_response_count{database=\"$database\",container=\"ydb-dynamic\",status!=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}